### PR TITLE
Improve HttpClient handling + minor improvements

### PR DESCRIPTION
**Pull request by theolivenbaum**
- Improve HttpClient handling
- Clean up Regex allocations
- Adapt tests to new code
- Add obsolete flag for Sync methods
- change String to string

### CODE REVIEW

**Comment by theolivenbaum** [comment]
Fixes #20 

@ftomassetti I've gone through the code and did some minor changes to reduce regex allocations, and changed a bit the logic for passing the custom HttpClient - it should instead receive a HttpClientHandler, and instantiate the HttpClient as needed.
I've also changed a little the regex handling to avoid allocating new ones on every call.

**Comment by gabriele-tomassetti** [comment]
Thanks for your great contribution! I have just made a small change: I removed the obsolete notification for the synchronous methods. I know why they might be considered bad practice in some cases, but at the moment they do not cost anything to maintain, so I see no reason to obsolete them. However, I do agree that if we end up making substantial changes to the API of the library there will be a good reason to remove them.

**Comment by theolivenbaum** [comment]
Yeah I thought about adding it as a warning, just because you can easily
get on thread starvation issues when using sync over async - not that you
need to remove it from the library any time soon.

**Comment by gabriele-tomassetti** [comment]
That is a good point. I think I will start adding your observations in the documentation. In the meantime I will think about it. My issue is just that I do not want to force people to change their code, if it is still working for them.

**Pull request merged**
