### PR TITLE
Improve Code Quality 2

### PR DESCRIPTION
**Pull request by iamcarbon**
- Enables nullable
- Eliminates lots of allocations
- Replaces a regex with a HashSet (10x faster)
- Update various parsing and formatting methods to use an invariant culture
- Reduce lookups (for dictionaries and attributes)
- Replace custom html entity decoding logic with HttpUtility.HtmlDecode
- Use built in mime map from AngleSharp

The test library runs around 11% faster for me after these changes.

### CODE REVIEW

**Comment by iamcarbon** [comment]
Ready for review / feedback.

**Review by gabriele-tomassetti — COMMENTED** [review]
I like all other changes, but I am not sure 7b03e210514ceabb5d797eb386b996da6088f360 is an improvement:

1. I cannot find any mention of the source of the list of MIME Types from AngleSharp, while MimeMapping mentions Apache Server and H5BP, which seems sensible choices. It also seems to supports more MIME types
2. While this removes a dependency, MimeMapping is a small dependency with little impact. The only relevant impact would probably be in an enterprise setting, where there might be requirements or checks necessary for every dependency. However, I do not think that SmartReader itself is much used in enterprise settings

What do you think @iamcarbon ?

**Comment by iamcarbon** [comment]
@gabriele-tomassetti

I've been working on reviewing this code (and it's dependencies) to include in a desktop application. Minimizing the dependencies certainly simplifies the work here. 

I've gone ahead and reverted this commit, but would like to propose this change again when AngleSharp updates to 0.16.0 with improved mime support. We should only need a small number of web formats rather then support for 1,000+ mappings.

I've also started the process for making these are tested upstream in the AngleSharp project.

https://github.com/AngleSharp/AngleSharp/commit/07496d23acd4e6f4f30b343b8c9e172d71c9d562

**Comment by gabriele-tomassetti** [comment]
@iamcarbon since you have a specific valid use case in mind I think that makes sense. Let's remove the dependency when AngleSharp updates to the improved mime support.

**Pull request merged**
